:bowtie:	smile	:smile:
top	laughing	:laughing:	blush	:blush:
top	smiley	:smiley:	relaxed	:relaxed:
top	smirk	:smirk:	heart_eyes	:heart_eyes:
top	kissing_heart	:kissing_heart:	kissing_closed_eyes	:kissing_closed_eyes:
top	flushed	:flushed:	relieved	:relieved:
top	laughing	:satisfied:	grin	:grin:
top	wink	:wink:	stuck_out_tongue_winking_eye	:stuck_out_tongue_winking_eye:
top	stuck_out_tongue_closed_eyes	:stuck_out_tongue_closed_eyes:	grinning	:grinning:
top	kissing	:kissing:	kissing_smiling_eyes	:kissing_smiling_eyes:
top	stuck_out_tongue	:stuck_out_tongue:	sleeping	:sleeping:
top	worried	:worried:	frowning	:frowning:
top	anguished	:anguished:	open_mouth	:open_mouth:
top	grimacing	:grimacing:	confused	:confused:
top	hushed	:hushed:	expressionless	:expressionless:
top	unamused	:unamused:	sweat_smile	:sweat_smile:
top	sweat	:sweat:	disappointed_relieved	:disappointed_relieved:
top	weary	:weary:	pensive	:pensive:
top	disappointed	:disappointed:	confounded	:confounded:
top	fearful	:fearful:	cold_sweat	:cold_sweat:
top	persevere	:persevere:	cry	:cry:
top	sob	:sob:	joy	:joy:
top	astonished	:astonished:	scream	:scream:
top	:neckbeard:	:neckbeard:	tired_face	:tired_face:
top	angry	:angry:	rage	:rage:
top	triumph	:triumph:	sleepy	:sleepy:
top	yum	:yum:	mask	:mask:
top	sunglasses	:sunglasses:	dizzy_face	:dizzy_face:
top	imp	:imp:	smiling_imp	:smiling_imp:
top	neutral_face	:neutral_face:	no_mouth	:no_mouth:
top	innocent	:innocent:	alien	:alien:
top	yellow_heart	:yellow_heart:	blue_heart	:blue_heart:
top	purple_heart	:purple_heart:	heart	:heart:
top	green_heart	:green_heart:	broken_heart	:broken_heart:
top	heartbeat	:heartbeat:	heartpulse	:heartpulse:
top	two_hearts	:two_hearts:	revolving_hearts	:revolving_hearts:
top	cupid	:cupid:	sparkling_heart	:sparkling_heart:
top	sparkles	:sparkles:	star	:star:
top	star2	:star2:	dizzy	:dizzy:
top	boom	:boom:	boom	:collision:
top	anger	:anger:	exclamation	:exclamation:
top	question	:question:	grey_exclamation	:grey_exclamation:
top	grey_question	:grey_question:	zzz	:zzz:
top	dash	:dash:	sweat_drops	:sweat_drops:
top	notes	:notes:	musical_note	:musical_note:
top	fire	:fire:	hankey	:hankey:
top	hankey	:poop:	hankey	:shit:
top	+1	:+1:	+1	:thumbsup:
top	-1	:-1:	-1	:thumbsdown:
top	ok_hand	:ok_hand:	fist_oncoming	:punch:
top	fist_oncoming	:facepunch:	fist_raised	:fist:
top	v	:v:	wave	:wave:
top	hand	:hand:	hand	:raised_hand:
top	open_hands	:open_hands:	point_up	:point_up:
top	point_down	:point_down:	point_left	:point_left:
top	point_right	:point_right:	raised_hands	:raised_hands:
top	pray	:pray:	point_up_2	:point_up_2:
top	clap	:clap:	muscle	:muscle:
top	metal	:metal:	middle_finger	:fu:
top	running_man	:runner:	running_man	:running:
top	couple	:couple:	family_man_woman_boy	:family:
top	two_men_holding_hands	:two_men_holding_hands:	two_women_holding_hands	:two_women_holding_hands:
top	dancer	:dancer:	dancing_women	:dancers:
top	ok_woman	:ok_woman:	no_good_woman	:no_good:
top	tipping_hand_woman	:information_desk_person:	raising_hand_woman	:raising_hand:
top	bride_with_veil	:bride_with_veil:	pouting_woman	:person_with_pouting_face:
top	frowning_woman	:person_frowning:	bowing_man	:bow:
top	couple_with_heart_woman_man	:couple_with_heart:	massage_woman	:massage:
top	haircut_woman	:haircut:	nail_care	:nail_care:
top	boy	:boy:	girl	:girl:
top	woman	:woman:	man	:man:
top	baby	:baby:	older_woman	:older_woman:
top	older_man	:older_man:	blonde_man	:person_with_blond_hair:
top	man_with_gua_pi_mao	:man_with_gua_pi_mao:	man_with_turban	:man_with_turban:
top	construction_worker_man	:construction_worker:	policeman	:cop:
top	angel	:angel:	princess	:princess:
top	smiley_cat	:smiley_cat:	smile_cat	:smile_cat:
top	heart_eyes_cat	:heart_eyes_cat:	kissing_cat	:kissing_cat:
top	smirk_cat	:smirk_cat:	scream_cat	:scream_cat:
top	crying_cat_face	:crying_cat_face:	joy_cat	:joy_cat:
top	pouting_cat	:pouting_cat:	japanese_ogre	:japanese_ogre:
top	japanese_goblin	:japanese_goblin:	see_no_evil	:see_no_evil:
top	hear_no_evil	:hear_no_evil:	speak_no_evil	:speak_no_evil:
top	guardsman	:guardsman:	skull	:skull:
top	feet	:feet:	lips	:lip
